#-----------------------------------------------------------------------------
# Purpose: intermedate includer makefile
ifeq ($(INC_PART),)
$(if $(MAKECMDGOALS),$(MAKECMDGOALS),all):
	@make -C .. $@
endif
